[2022-08-11 20:19:29,227] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2022-08-10T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'format_to_parquet_task'}
[2022-08-11 20:19:29,232] {local_task_job.py:99} INFO - Task is not able to be run
[2022-08-11 20:19:45,304] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2022-08-10T00:00:00+00:00 [queued]>
[2022-08-11 20:19:45,342] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2022-08-10T00:00:00+00:00 [queued]>
[2022-08-11 20:19:45,344] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 20:19:45,345] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-08-11 20:19:45,347] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 20:19:45,386] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-08-10 00:00:00+00:00
[2022-08-11 20:19:45,405] {standard_task_runner.py:52} INFO - Started process 1249 to run task
[2022-08-11 20:19:45,413] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2022-08-10T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gpc.py', '--cfg-path', '/tmp/tmpouyk4br1', '--error-file', '/tmp/tmpyje7flwi']
[2022-08-11 20:19:45,416] {standard_task_runner.py:77} INFO - Job 87: Subtask local_to_gcs_task
[2022-08-11 20:19:45,541] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2022-08-10T00:00:00+00:00 [running]> on host a96959784c93
[2022-08-11 20:19:45,687] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-10T00:00:00+00:00
[2022-08-11 20:19:45,691] {logging_mixin.py:109} INFO - /opt/***/yellow_tripdata_2021-01.csv
[2022-08-11 20:20:40,978] {python.py:175} INFO - Done. Returned value was: None
[2022-08-11 20:20:41,059] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20220810T000000, start_date=20220811T201945, end_date=20220811T202041
[2022-08-11 20:20:41,209] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-11 20:20:41,323] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
